# Generated by Django 3.0.6 on 2020-05-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torsion_shop', '0003_auto_20200505_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='online_order',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='price_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='price_language',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='price_schedule',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='send_price',
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/content_image/'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='manager',
            name='skype',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='manager',
            name='source_id',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/product_image/'),
        ),
    ]
