# Generated by Django 3.0.6 on 2020-05-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torsion_shop', '0004_auto_20200505_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeragreement',
            name='price_available',
        ),
        migrations.RemoveField(
            model_name='customeragreement',
            name='price_email',
        ),
        migrations.RemoveField(
            model_name='customeragreement',
            name='price_language',
        ),
        migrations.RemoveField(
            model_name='customeragreement',
            name='price_schedule',
        ),
    ]
