# Generated by Django 2.2.13 on 2020-07-15 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=300, unique=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.today)),
                ('updated_date', models.DateTimeField(default=datetime.datetime.today)),
                ('published', models.BooleanField(default=0)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='content/main_image/')),
                ('title', models.CharField(max_length=500, null=True)),
                ('intro_text', models.CharField(max_length=1000, null=True)),
                ('full_text', models.TextField(null=True)),
                ('meta_tag_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_tag_description', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_tag_keyword', models.CharField(blank=True, max_length=500, null=True)),
                ('geo', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Aboutus',
                'verbose_name_plural': 'Aboutus',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=300, unique=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.today)),
                ('updated_date', models.DateTimeField(default=datetime.datetime.today)),
                ('published', models.BooleanField(default=0)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='content/main_image/')),
                ('title', models.CharField(max_length=500, null=True)),
                ('intro_text', models.CharField(max_length=1000, null=True)),
                ('full_text', models.TextField(null=True)),
                ('meta_tag_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_tag_description', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_tag_keyword', models.CharField(blank=True, max_length=500, null=True)),
                ('geo', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=300, unique=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.today)),
                ('updated_date', models.DateTimeField(default=datetime.datetime.today)),
                ('published', models.BooleanField(default=0)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='content/main_image/')),
                ('title', models.CharField(max_length=500, null=True)),
                ('intro_text', models.CharField(max_length=1000, null=True)),
                ('full_text', models.TextField(null=True)),
                ('meta_tag_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_tag_description', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_tag_keyword', models.CharField(blank=True, max_length=500, null=True)),
                ('geo', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
