# Generated by Django 3.0.6 on 2020-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torsion_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='gallery_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
