# Generated by Django 3.0.6 on 2020-05-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torsion_shop', '0002_auto_20200505_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='source_type',
            field=models.CharField(blank=True, default='1C', max_length=250, null=True),
        ),
    ]
